services:
  - type: web
    name: dashboard-ekraf-malang
    runtime: image
    region: singapore
    healthCheckPath: /healthz
    autoDeployTrigger: off
    image:
      url: ghcr.io/afrzlfaiz/flask-dashboard-ekraf:latest
      creds:
        fromRegistryCreds:
          name: ghcr-dashboard-ekraf
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: BOOTSTRAP_ADMIN_USERNAME
        sync: false
      - key: BOOTSTRAP_ADMIN_PASSWORD
        sync: false
